% This is just a list of all the variables for reference.

rsna          = x(1 ); rsna_p          = x_p(1 ); 
alpha_map     = x(2 ); alpha_map_p     = x_p(2 ); 
alpha_rap     = x(3 ); alpha_rap_p     = x_p(3 ); 
R_r           = x(4 ); R_r_p           = x_p(4 ); 
beta_rsna     = x(5 ); beta_rsna_p     = x_p(5 ); 
Phi_rb        = x(6 ); Phi_rb_p        = x_p(6 ); 
Phi_gfilt     = x(7 ); Phi_gfilt_p     = x_p(7 ); 
P_f           = x(8 ); P_f_p           = x_p(8 ); 
P_gh          = x(9 ); P_gh_p          = x_p(9 ); 
Sigma_tgf     = x(10); Sigma_tgf_p     = x_p(10); 
Phi_filsod    = x(11); Phi_filsod_p    = x_p(11); 
Phi_ptsodreab = x(12); Phi_ptsodreab_p = x_p(12); 
eta_ptsodreab = x(13); eta_ptsodreab_p = x_p(13); 
gamma_filsod  = x(14); gamma_filsod_p  = x_p(14); 
gamma_at      = x(15); gamma_at_p      = x_p(15); 
gamma_rsna    = x(16); gamma_rsna_p    = x_p(16); 
Phi_mdsod     = x(17); Phi_mdsod_p     = x_p(17); 
Phi_dtsodreab = x(18); Phi_dtsodreab_p = x_p(18); 
eta_dtsodreab = x(19); eta_dtsodreab_p = x_p(19); 
psi_al        = x(20); psi_al_p        = x_p(20); 
Phi_dtsod     = x(21); Phi_dtsod_p     = x_p(21); 
Phi_cdsodreab = x(22); Phi_cdsodreab_p = x_p(22); 
eta_cdsodreab = x(23); eta_cdsodreab_p = x_p(23); 
lambda_dt     = x(24); lambda_dt_p     = x_p(24); 
lambda_anp    = x(25); lambda_anp_p    = x_p(25); 
Phi_usod      = x(26); Phi_usod_p      = x_p(26); 
Phi_win       = x(27); Phi_win_p       = x_p(27); 
V_ecf         = x(28); V_ecf_p         = x_p(28); 
V_b           = x(29); V_b_p           = x_p(29); 
P_mf          = x(30); P_mf_p          = x_p(30); 
Phi_vr        = x(31); Phi_vr_p        = x_p(31); 
Phi_co        = x(32); Phi_co_p        = x_p(32); 
P_ra          = x(33); P_ra_p          = x_p(33); 
vas           = x(34); vas_p           = x_p(34); 
vas_f         = x(35); vas_f_p         = x_p(35); 
vas_d         = x(36); vas_d_p         = x_p(36); 
R_a           = x(37); R_a_p           = x_p(37); 
R_ba          = x(38); R_ba_p          = x_p(38); 
R_vr          = x(39); R_vr_p          = x_p(39); 
R_tp          = x(40); R_tp_p          = x_p(40); 
P_ma          = x(41); P_ma_p          = x_p(41); 
epsilon_aum   = x(42); epsilon_aum_p   = x_p(42); 
a_auto        = x(43); a_auto_p        = x_p(43); 
a_chemo       = x(44); a_chemo_p       = x_p(44); 
a_baro        = x(45); a_baro_p        = x_p(45); 
C_adh         = x(46); C_adh_p         = x_p(46); 
N_adh         = x(47); N_adh_p         = x_p(47); 
N_adhs        = x(48); N_adhs_p        = x_p(48); 
delta_ra      = x(49); delta_ra_p      = x_p(49); 
Phi_twreab    = x(50); Phi_twreab_p    = x_p(50); 
mu_al         = x(51); mu_al_p         = x_p(51); 
mu_adh        = x(52); mu_adh_p        = x_p(52); 
Phi_u         = x(53); Phi_u_p         = x_p(53); 
M_sod         = x(54); M_sod_p         = x_p(54); 
C_sod         = x(55); C_sod_p         = x_p(55); 
nu_mdsod      = x(56); nu_mdsod_p      = x_p(56); 
nu_rsna       = x(57); nu_rsna_p       = x_p(57); 
C_al          = x(58); C_al_p          = x_p(58); 
N_al          = x(59); N_al_p          = x_p(59); 
N_als         = x(60); N_als_p         = x_p(60); 
xi_ksod       = x(61); xi_ksod_p       = x_p(61); 
xi_map        = x(62); xi_map_p        = x_p(62); 
xi_at         = x(63); xi_at_p         = x_p(63); 
hatC_anp      = x(64); hatC_anp_p      = x_p(64); 
AGT           = x(65); AGT_p           = x_p(65); 
nu_AT1        = x(66); nu_AT1_p        = x_p(66); 
R_sec         = x(67); R_sec_p         = x_p(67); 
PRC           = x(68); PRC_p           = x_p(68); 
PRA           = x(69); PRA_p           = x_p(69); 
AngI          = x(70); AngI_p          = x_p(70); 
AngII         = x(71); AngII_p         = x_p(71); 
AT1R          = x(72); AT1R_p          = x_p(72); 
AT2R          = x(73); AT2R_p          = x_p(73); 
Ang17         = x(74); Ang17_p         = x_p(74); 
AngIV         = x(75); AngIV_p         = x_p(75); 
R_aa          = x(76); R_aa_p          = x_p(76); 
R_ea          = x(77); R_ea_p          = x_p(77); 
Sigma_myo     = x(78); Sigma_myo_p     = x_p(78); 
Psi_AT1RAA    = x(79); Psi_AT1RAA_p    = x_p(79); 
Psi_AT1REA    = x(80); Psi_AT1REA_p    = x_p(80); 
Psi_AT2RAA    = x(81); Psi_AT2RAA_p    = x_p(81); 
Psi_AT2REA    = x(82); Psi_AT2REA_p    = x_p(82); 