
%% read in data
human = 1;% 1 for human, 0 for rat
species = {'rat','human'};
gender   = {'male', 'female'};
num_days = 2;
tchange = 100;

models = [0,0,0;...
    1,0,0;...
    0,1,0;...
    0,0,1;...
    1,1,0;...
    0,1,1;...
    1,0,1;...
    1,1,1];
%models = 2*models; %for high dose simulations
treatments_to_run = 1:8;
sex_to_run = 1:2;
hyp = [1,2.5];
for gg = sex_to_run %sex
    for mm= treatments_to_run 
        for AA = 1:length(hyp)
            filename = '%s%s_%s_%s_%s_%s_%s.mat';
            filename = sprintf( filename,'Data/',species{human+1},gender{gg},num2str(models(mm,1)),num2str(models(mm,2)),num2str(models(mm,3)),num2str(hyp(AA)));
            load(filename, 't','x');
            T{gg,mm,AA} = t;
            X{gg,mm,AA} = x;
            tf = t(end);
        end
    end
end




names  = {'$rsna$'; '$\alpha_{map}$'; '$\alpha_{rap}$'; '$R_{r}$'; ...
      '$\beta_{rsna}$'; '$\Phi_{rb}$'; 'GFR'; '$P_{f}$'; ...
      '$P_{gh}$'; '$\Sigma_{tgf}$'; '$\Phi_{filsod}$'; ...
      '$\Phi_{pt-sodreab}$'; '$\eta_{pt-sodreab}$'; ...
      '$\gamma_{filsod}$'; '$\gamma_{at}$'; '$\gamma_{rsna}$'; ...
      '$\Phi_{md-sod}$'; '$\Phi_{dt-sodreab}$'; ...
      '$\eta_{dt-sodreab}$'; '$\psi_{al}$'; '$\Phi_{dt-sod}$'; ...
      '$\Phi_{cd-sodreab}$'; '$\eta_{cd-sodreab}$'; ...
      '$\lambda_{al}$';'$\lambda_{dt}$'; '$\lambda_{anp}$'; '$\Phi_{u-sod}$'; ...
      '$\Phi_{win}$'; '$V_{ecf}$'; '$V_{b}$'; '$P_{mf}$'; ...
      '$\Phi_{vr}$'; '$\Phi_{co}$'; '$P_{ra}$'; '$vas$'; ...
      '$vas_{f}$'; '$vas_{d}$'; '$R_{a}$'; '$R_{ba}$'; '$R_{vr}$'; ...
      '$R_{tp}$'; '$P_{ma}$'; '$\epsilon_{aum}$'; '$a_{auto}$'; ...
      '$a_{chemo}$'; '$a_{baro}$'; '$C_{adh}$'; '$N_{adh}$'; ...
      '$N_{adhs}$'; '$\delta_{ra}$'; '$\Phi_{u}$'; '$M_{sod}$'; ...
      '$C_{sod}$'; '$\nu_{md-sod}$'; '$\nu_{rsna}$'; '$C_{al}$'; ...
      '$N_{al}$'; '$N_{als}$'; '$\xi_{k/sod}$'; '$\xi_{map}$'; ...
      '$\xi_{at}$'; '$\hat{C}_{anp}$'; '$AGT$'; '$\nu_{AT1}$'; ...
      '$R_{sec}$'; '$PRC$'; '$PRA$'; '$Ang I$'; '$Ang II$'; ...
      '$Ang II_{AT1R-bound}$'; '$Ang II_{AT2R-bound}$'; ...
      '$Ang (1-7)$'; '$Ang IV$'; '$R_{aa}$'; '$R_{ea}$'; ...
      '$\Sigma_{myo}$'; '$\Psi_{AT1R-AA}$'; '$\Psi_{AT1R-EA}$'; ...
      '$\Psi_{AT2R-AA}$'; '$\Psi_{AT2R-EA}$';'$\Phi_{sodin}$';...
      '$\Phi_{t-wreab}$'; ...
      '$\mu_{adh}$'; '$\mu_{Na}$';};
plot_these = [7,42,51,67];
ylim_labels = {'l/min','mmHg','l/min','fmol/ml/min'}; 
label_names = {'GFR','MAP','Urine Flow','PRA'};
linecolor = {'g';'b';'r'};
markerstyle = {'o';'+';'*';'X';'s';'d';'^';'p'};
linestyle = {'-','--','--','--',':',':',':','-'};
ylimits = [0.06,0.16;...
   80,165;...
   0,0.01;...
   10,60];
f = gobjects(length(plot_these),1);
titles = {'Male','Female','M HTN','F HTN'};
data = zeros(length(plot_these),8,2*2,num_days);
for i = 1:length(plot_these)
    f(i) = figure;


    for gg= sex_to_run
        for AA = 1:length(hyp)
            s(AA,gg) = subplot(1,4,2*(AA-1)+gg);
            %disp([AA,gg,2*(AA-1)+gg])
            for mm = treatments_to_run
                x1=X{gg,mm,AA};  
                t = T{gg,mm,AA};
                if t(end) > tchange
                    for dd = 1:(num_days)
                        mask1 = (t>tchange+(dd-1)*1440);
                        mask2 = (t < tchange + dd*1440);
                        mask = mask1&mask2;
                        day = t(mask);
                        dt = day(2:end) - day(1:end-1);
                        x_day = x1(mask,plot_these(i));
                        ave = sum(dt .* x_day(2:end))/(day(end) - day(1));
                        data(i,mm,2*(AA-1) + gg,dd) = ave;
                    end
                else
                    data(i,mm,2*(AA-1) + gg,:) = zeros(1,num_days);
                end
                plot(1:num_days,reshape(data(i,mm,2*(AA-1)+gg,:),[1,num_days]),...
                     sprintf('%s%s',linestyle{mm},markerstyle{mm}),...
                    'Color',linecolor{mod(mm,3)+1},...
                    'LineWidth',2,...
                    'MarkerSize',10,...
                     'MarkerEdgeColor','black',...
                     'MarkerFaceColor',linecolor{mod(mm,3)+1})
                hold on
            end
            xlim([0.7,num_days+0.3])
            xticks(1:num_days)                       
            ylim(ylimits(i,:))
            title(titles{2*(AA-1)+gg})%names{plot_these(i)}, 'Interpreter','latex')%, 'FontSize',24)
            if (2*(AA-1)+gg) ==1
                 ylabel(sprintf('%s (%s)',label_names{i},ylim_labels{i}))
            else 
                yticklabels([])
            end
            set(gca,'YGrid','on','Fontsize',16)

            if i==3
             hline(0.0003,'k','AKI')
                %hline(0.001)
            end
                xlabel('Day')
                %xticklabels(num2str(1:numdays))

        end
    end
    %legend({'Control','ACEI','Furosemide','NSAID',...
    %    'A+F','F+N','A+N','A+F+N'})

end
savefig(f, sprintf('Figures/%s_scatter.fig',species{human+1}))